services:
  traefik:
    image: traefik:latest
    command:
      - --configFile=/etc/traefik/traefik.yml
    ports:
      - "${TRAEFIK_HTTP_PORT:-80}:80"
      # Traefik dashboard (dev only):
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./traefik/traefik.yml:/etc/traefik/traefik.yml:ro
    networks:
      - edge

  web:
    image: nginx:latest
    # Test to see if load balancing is working by customizing the index.html on container start
    command: /bin/sh -c "echo \"<h1>Served by $(hostname)</h1>\" > /usr/share/nginx/html/index.html && nginx -g 'daemon off;'"
    networks:
      - edge
    labels:
      - traefik.enable=true
      - traefik.http.routers.web.rule=PathPrefix(`/`)
      - traefik.http.routers.web.entrypoints=web
      - traefik.http.services.web.loadbalancer.server.port=80
      - traefik.http.routers.web.priority=1

  api:
    build:
      context: ./order-processor
    environment:
      - PORT=${API_PORT:-3000}
      - MYSQL_HOST=db
      - MYSQL_PORT=3306
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    depends_on:
      db:
        condition: service_healthy
    networks:
      - edge
      - internal
    labels:
      - traefik.enable=true

      # Route "/api" -> NodeJS
      - traefik.http.routers.api.rule=PathPrefix(`/api`)
      - traefik.http.routers.api.entrypoints=web
      - traefik.http.routers.api.priority=10

      # Strip "/api" prefix before forwarding to the service
      - traefik.http.middlewares.api-strip.stripprefix.prefixes=/api
      - traefik.http.routers.api.middlewares=api-strip

      - traefik.http.services.api.loadbalancer.server.port=${API_PORT:-3000}

  db:
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    volumes:
      - dbdata:/var/lib/mysql
      - ./db/init:/docker-entrypoint-initdb.d:ro
    networks:
      - internal
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "127.0.0.1", "-p${MYSQL_ROOT_PASSWORD}"]
      interval: 5s
      timeout: 3s
      retries: 30

networks:
  edge:
    name: oms_edge
  internal:
    name: oms_internal

volumes:
  dbdata:
    name: oms_dbdata
